#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys, os
import pathlib
p = pathlib.Path(os.path.dirname(__file__) + '/..')
root_dir_path = str(p.resolve())
sys.path.append(root_dir_path)
import numpy as np

from src import (
    mnist, networks, optimizers, trainers, viewers
)

import yaml


if __name__ == '__main__':
    fd = open(root_dir_path + '/config/train.yaml')
    yaml_node = yaml.load(fd)

    network = networks.create_multilayer_network(yaml_node['neural_network'])

    optimizer = optimizers.create(yaml_node['optimizer'])

    (x_train, t_train), (x_test, t_test) = mnist.load_mnist(one_hot_label=True)

    viewer = viewers.create(yaml_node['plot'], network.params)

    trainer = trainers.create(yaml_node['trainer'], network, optimizer,
                              x_train, t_train, x_test, t_test, viewer.view)

    trainer.train()
    input()
