#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys, os
import pathlib
p = pathlib.Path(os.path.dirname(__file__) + '/..')
root_dir_path = str(p.resolve())
sys.path.append(root_dir_path)
import numpy as np

from src import (
    mnist, networks, optimizers, trainers, viewers
)

import yaml


if __name__ == '__main__':
    fd = open(root_dir_path + '/config/train_cnn.yaml')
    yaml_node = yaml.load(fd)

    network = networks.create_simple_cnn(yaml_node['neural_network'])

    optimizer = optimizers.create(yaml_node['optimizer'])

    (x_train, t_train), (x_test, t_test) = mnist.load_mnist(flatten=False)

    viewer = viewers.create(yaml_node['plot'], network.params)

    trainer = trainers.create(yaml_node['trainer'], network, optimizer,
                              x_train, t_train, x_test, t_test, viewer.view)

    trainer.train()

    print('Save model ? [y/N]')
    user_input = input()
    input_to_save = ['y', 'yes', 'Yes', 'YES']
    if user_input in input_to_save:
        output_filename = '/tmp/params.pkl'
        network.save_params(output_filename)
        print('Output model as {}'.format(output_filename))

    print('Hit enter key to exit')
    input()
